services:
  db:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
      POSTGRES_DB: ${POSTGRES_DB:-acechat}
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - ${APP_PORT:-3000}:3000
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-mysecretpassword}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-acechat}}
      UPLOAD_DIR: ${UPLOAD_DIR:-/app/uploads}
      ORIGIN: ${ORIGIN:-http://localhost:3000}
    volumes:
      - uploads:/app/uploads
    depends_on:
      - db

volumes:
  pgdata:
  uploads:
